### ISSUE TITLE
ToDo List for opTagCache

### ISSUE THREAD

**Issue by wsong83** [lowRISC/uncore#2]
- [ ] tagged/untagged run-time learning
- [x] enforce temporal order
- [ ] check write-back condition
- [ ] check enable/disable early ack
- [ ] bank tag transaction trackers
- [No] share beat array between memory transaction trackers

comments:
The shared beat array among trackers should be able to handle interleaved burst transactions.
